name: 'Verify Build And Plan'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-job:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    name: CI - Build Verify
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Install PNPM
        run: |
          npm install -g pnpm

      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm store prune
          pnpm build
          
      - name: Docker Build
        run : |
          docker build -t ci -f Dockerfile .
